const data = [
	{"name":"Bagel and cream cheese", "title":"How we dream about our future", "price":6.99, "url":"https://i.ibb.co/XtgTzw4/breakfast4.png" ,"category":"breakfast"},
	{"name":"Breakfast sandwich", "title":"Good morning! Have a nice day", "price":9.99, "url":"https://i.ibb.co/z2XZbJp/breakfast2.png" ,"category":"breakfast"},
	{"name":"Baked chicken", "title":"Good food, Healthy life", "price":10.99, "url":"https://i.ibb.co/4NCSGXs/breakfast3.png", "category":"breakfast"},
	{"name":"Eggs benedict", "title":"Never give up, take care yourself", "price":8.99, "url":"https://i.ibb.co/3fRPQSW/breakfast1.png", "category":"breakfast"},
	{"name":"Toast croissant fried egg", "title":"Protin power booster", "price":15.99, "url":"https://i.ibb.co/b7fWWtb/breakfast6.png", "category":"breakfast"},
	{"name":"Fried egg toast brunch", "title":"Standard breakfast for everyone", "price":3.99, "url":"https://i.ibb.co/CMFLCF3/breakfast5.png", "category":"breakfast"},
    {"name":"Healthy Meal Plan", "title":"How we dream about our future", "price":9.99, "url":"https://i.ibb.co/6gjTqSJ/lunch6.png", "category":"lunch"},
	{"name":"Fried Chicken Bento", "title":"Good noon! Have a nice day", "price":19.99, "url":"https://i.ibb.co/R7wrKwp/lunch5.png", "category":"lunch"},
	{"name":"Tarragon Rubbed Salmon", "title":"Good food, Healthy life", "price":6.99, "url":"https://i.ibb.co/xCfTHyV/lunch3.png", "category":"lunch"},
	{"name":"Indian Lunch", "title":"Never give up, take care yourself", "price":13.99, "url":"https://i.ibb.co/vVnfbMd/lunch4.png", "category":"lunch"},
	{"name":"Beef Steak", "title":"Protin power booster", "price":14.99, "url":"https://i.ibb.co/Jm1GbDY/lunch1.png", "category":"lunch"},
	{"name":"Honey Soy Glazed With Peppers", "title":"Lunch for everyone", "price":6.99, "url":"https://i.ibb.co/4487jMY/lunch2.png", "category":"lunch"},
    {"name":"Salmon with grapefruit and salad", "title":"How we dream about our future", "price":9.99, "url":"https://i.ibb.co/JscvQTQ/dinner6.png","category":"dinner"},
	{"name":"Lemon salmon piccata", "title":"Good evening! Have a nice night", "price":10.99, "url":"https://i.ibb.co/8rzRCG3/dinner2.png","category":"dinner"},
	{"name":"Pork tenderloin with quinoa pilaf", "title":"Good food, Healthy life", "price":12.99, "url":"https://i.ibb.co/KFy1tpm/dinner5.png","category":"dinner"},
	{"name":"Friench fries with cheese", "title":"Never give up, take care yourself", "price":8.99, "url":"https://i.ibb.co/LZtwCnZ/dinner4.png","category":"dinner"},
	{"name":"Garlic butter baked salmon", "title":"Protin power booster", "price":6.99, "url":"https://i.ibb.co/YLZLNhS/dinner3.png","category":"dinner"},
	{"name":"Baked chicken", "title":"Standard dinner for everyone", "price":9.99, "url":"https://i.ibb.co/Fsxj4B4/dinner1.png","category":"dinner"},
    {"name":"Black", "title":"Black coffee is as simple as it gets with ground coffee beans steeped in hot water, served warm. And if you want to sound fancy, you can call black coffee by its proper name: cafe noir.", "price":2.99, "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/640px-A_small_cup_of_coffee.JPG", "category":"coffee"},
    {"name":"Latte", "title":"As the most popular coffee drink out there, the latte is comprised of a shot of espresso and steamed milk with just a touch of foam. It can be ordered plain or with a flavor shot of anything from vanilla to pumpkin spice.", "price":3.99, "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg/509px-Latte_at_Doppio_Ristretto_Chiang_Mai_01.jpg", "category":"coffee"},
    {"name":"Cappuccino", "title":"Cappuccino is a latte made with more foam than steamed milk, often with a sprinkle of cocoa powder or cinnamon on top. Sometimes you can find variations that use cream instead of milk or ones that throw in flavor shot, as well.", "price":4.99, "url":"https://upload.wikimedia.org/wikipedia/commons/e/ed/Wet_Cappuccino_with_heart_latte_art.jpg", "category":"coffee"},
    {"name":"Americano", "title":"With a similar flavor to black coffee, the americano consists of an espresso shot diluted in hot water.", "price":5.99, "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Hokitika_Cheese_and_Deli%2C_Hokitika_%283526706594%29.jpg/1280px-Hokitika_Cheese_and_Deli%2C_Hokitika_%283526706594%29.jpg", "category":"coffee"},
    {"name":"Espresso", "title":"An espresso shot can be served solo or used as the foundation of most coffee drinks, like lattes and macchiatos.", "price":6.99, "url":"https://upload.wikimedia.org/wikipedia/commons/a/a5/Tazzina_di_caff%C3%A8_a_Ventimiglia.jpg", "category":"coffee"},
	{"name":"Mocha", "title":"For all you chocolate lovers out there, you’ll fall in love with a mocha (or maybe you already have). The mocha is a chocolate espresso drink with steamed milk and foam.", "price":7.99, "url":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Mocaccino-Coffee.jpg", "category":"coffee"},
]

export default data;
